import { NitroModules } from 'react-native-nitro-modules'
import type { DataScannerFactory } from './specs/DataScannerFactory.nitro'

export const DataScanner =
  NitroModules.createHybridObject<DataScannerFactory>('DataScannerFactory')

export type { DataScannerFactory } from './specs/DataScannerFactory.nitro'
export type {
  BarcodeAddress,
  BarcodeAddressType,
  BarcodeCalendarDateTime,
  BarcodeCalendarEvent,
  BarcodeContactInfo,
  BarcodeDriverLicense,
  BarcodeEmail,
  BarcodeEmailType,
  BarcodeFormat,
  BarcodeGeoPoint,
  BarcodePayload,
  BarcodePersonName,
  BarcodePhone,
  BarcodePhoneType,
  BarcodeRecognitionOptions,
  BarcodeSms,
  BarcodeUrl,
  BarcodeValueType,
  BarcodeWifi,
  BarcodeWifiEncryptionType,
  Bounds,
  CapturedPhoto,
  DataScanner as DataScannerInstance,
  DataScannerCapabilities,
  DataScannerConfiguration,
  ItemTappedEvent,
  ItemTappedListener,
  ItemsChangedEvent,
  ItemsChangedListener,
  ListenerSubscription,
  Point,
  QualityLevel,
  RecognizedDataTypes,
  Rect,
  ScannedBarcode,
  ScannedItem,
  ScannedItemType,
  ScannedText,
  ScannerErrorListener,
  TextContentType,
  TextRecognitionOptions,
  ZoomChangedEvent,
  ZoomChangedListener,
} from './specs/DataScanner.nitro'
