export { DataScanner, scan } from './DataScanner'
export type { DataScannerModule } from './DataScanner'
export type { ScanOptions, TargetBarcodeFormats } from './ScanOptions'
export type { Barcode } from './specs/Barcode'
export type { BarcodeFormat, TargetBarcodeFormat } from './specs/BarcodeFormat'
